version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:1.4.8
    volumes:
      - "/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/mosquitto/log:/mosquitto/log"
      - "/mosquitto/data/:/mosquitto/data/"
    ports:
      - "1883:1883"
      - "9000:9000"
